services:
  postgres:
    image: postgres:17
    container_name: lob-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: limit_order_book
    ports:
      - "5433:5432"
    volumes:
      - "lob_postgres_data:/var/lib/postgresql/data"
      
volumes:
  lob_postgres_data: